from typing import Protocol, BinaryIO
from pathlib import Path


class IFileStorage(Protocol):
    async def save(self, file: BinaryIO, original_name: str) -> Path: ...
    async def delete(self, path: Path) -> None: ...
    async def get_url(self, path: Path) -> str: ...
