from typing import Protocol

from src.application.shared.interfaces import IDbContext


class IUnitOfWork(Protocol):
    @property
    def context(self) -> IDbContext: ...

    async def __aenter__(self) -> "IUnitOfWork": ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
