"""Update User model

Revision ID: 4681c977a532
Revises: b5cf59c3fb65
Create Date: 2026-06-21 21:57:04.923994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4681c977a532'
down_revision: Union[str, Sequence[str], None] = 'b5cf59c3fb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint('nq_users_email', 'users', ['email'])
    op.create_unique_constraint('nq_users_username', 'users', ['username'])
    op.create_unique_constraint('uq_users_auth_provider_subject', 'users', ['auth_provider', 'auth_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_auth_provider_subject', 'users', type_='unique')
    op.drop_constraint('nq_users_username', 'users', type_='unique')
    op.drop_constraint('nq_users_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
