"""Rename responder to respondent in Quiz model

Revision ID: 7fb3d5c449d6
Revises: abc1e1c4b763
Create Date: 2026-06-22 18:01:34.777843

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7fb3d5c449d6'
down_revision: Union[str, Sequence[str], None] = 'abc1e1c4b763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'quizzes',
        'responder_id',
        new_column_name='respondent_id'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'quizzes',
        'respondent_id',
        new_column_name='responder_id'
    )
    # ### end Alembic commands ###
