"""Rename is_completed to is_published in Quiz model

Revision ID: abc1e1c4b763
Revises: 4681c977a532
Create Date: 2026-06-21 23:17:18.662741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc1e1c4b763'
down_revision: Union[str, Sequence[str], None] = '4681c977a532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'quizzes',
        'is_completed',
        new_column_name='is_published'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'quizzes',
        'is_published',
        new_column_name='is_completed'
    )
    # ### end Alembic commands ###
