"""Add new fields to quiz

Revision ID: ec113c903ad4
Revises: 7fb3d5c449d6
Create Date: 2026-06-25 17:57:36.144137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec113c903ad4'
down_revision: Union[str, Sequence[str], None] = '7fb3d5c449d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('current_question_id', sa.Uuid(), nullable=True))
    op.drop_column('quizzes', 'has_viewed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('has_viewed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('quizzes', 'current_question_id')
    op.drop_column('quizzes', 'published_at')
    # ### end Alembic commands ###
